/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import { Scene } from "laya/display/Scene";
import { ClassUtils } from "laya/utils/ClassUtils";
var REG: Function = ClassUtils.regClass;
import { FrameAnimation } from "laya/display/FrameAnimation";
import { EffectAnimation } from "laya/display/EffectAnimation";
import { View } from "laya/ui/View";
import { Image } from "laya/ui/Image";
export module ui {
    export class animMoveUI extends EffectAnimation {
		public ani1:FrameAnimation;
        public static  uiView:any ={"type":"View","props":{},"compId":2,"child":[{"type":"Image","props":{"y":0,"x":0,"skin":"ui/箭头.png","anchorY":0.5,"anchorX":0.5},"compId":3}],"animations":[{"nodes":[{"target":3,"keyframes":{"y":[{"value":0,"tweenMethod":"linearNone","tween":true,"target":3,"key":"y","index":0},{"value":15,"tweenMethod":"linearNone","tween":true,"target":3,"key":"y","index":5},{"value":0,"tweenMethod":"linearNone","tween":true,"target":3,"key":"y","index":10}],"x":[{"value":0,"tweenMethod":"linearNone","tween":true,"target":3,"key":"x","index":0}]}}],"name":"ani1","id":1,"frameRate":24,"action":0}],"loadList":["ui/箭头.png"],"loadList3D":[]};
        public referenceClass:Array<any>=[FrameAnimation, EffectAnimation, View, Image]; // 强制引用类,防止被编译器忽略
		constructor(){ super();this.effectData =ui.animMoveUI.uiView;}
    }
    REG("ui.animMoveUI",animMoveUI);
    export class scaleBtnUI extends EffectAnimation {
		public ani1:FrameAnimation;
        public static  uiView:any ={"type":"View","props":{},"compId":2,"child":[{"type":"Image","props":{"y":-1,"x":-1,"width":241,"skin":"ui/烧制.png","height":187,"anchorY":0.5,"anchorX":0.5},"compId":4}],"animations":[{"nodes":[{"target":4,"keyframes":{"scaleY":[{"value":1,"tweenMethod":"linearNone","tween":true,"target":4,"key":"scaleY","index":0},{"value":1.2,"tweenMethod":"linearNone","tween":true,"target":4,"key":"scaleY","index":10},{"value":1,"tweenMethod":"linearNone","tween":true,"target":4,"key":"scaleY","index":20}],"scaleX":[{"value":1,"tweenMethod":"linearNone","tween":true,"target":4,"key":"scaleX","index":0},{"value":1.2,"tweenMethod":"linearNone","tween":true,"target":4,"key":"scaleX","index":10},{"value":1,"tweenMethod":"linearNone","tween":true,"target":4,"key":"scaleX","index":20}]}}],"name":"ani1","id":1,"frameRate":24,"action":0}],"loadList":["ui/烧制.png"],"loadList3D":[]};
        public referenceClass:Array<any>=[FrameAnimation, EffectAnimation, View, Image]; // 强制引用类,防止被编译器忽略
		constructor(){ super();this.effectData =ui.scaleBtnUI.uiView;}
    }
    REG("ui.scaleBtnUI",scaleBtnUI);
    export class scaleStarUI extends EffectAnimation {
		public ani1:FrameAnimation;
		public star:Image;
        public static  uiView:any ={"type":"View","props":{},"compId":2,"child":[{"type":"Image","props":{"y":0,"x":0,"var":"star","skin":"ui/星星-黄色.png","anchorY":0.5,"anchorX":0.5},"compId":3}],"animations":[{"nodes":[{"target":3,"keyframes":{"scaleY":[{"value":1,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleY","index":0},{"value":1.3,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleY","index":15},{"value":1,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleY","index":30}],"scaleX":[{"value":1,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleX","index":0},{"value":1.3,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleX","index":15},{"value":1,"tweenMethod":"linearNone","tween":true,"target":3,"key":"scaleX","index":30}]}}],"name":"ani1","id":1,"frameRate":24,"action":0}],"loadList":["ui/星星-黄色.png"],"loadList3D":[]};
        public referenceClass:Array<any>=[FrameAnimation, Image, EffectAnimation, View]; // 强制引用类,防止被编译器忽略
		constructor(){ super();this.effectData =ui.scaleStarUI.uiView;}
    }
    REG("ui.scaleStarUI",scaleStarUI);
}
import { Button } from "laya/ui/Button";
import { Sprite } from "laya/display/Sprite";
import { Label } from "laya/ui/Label";
import { List } from "laya/ui/List";
import { Clip } from "laya/ui/Clip";
import { Box } from "laya/ui/Box";
export module ui.test {
    export class lightAnimSceneUI extends View {
		public bg:Image;
		public center:Image;
		public fire1:Image;
		public fire2:Image;
		public fire3:Image;
		public fire4:Image;
		public greenNode:Image;
		public greenMask:Image;
		public nodepointer:Image;
		public centerNode:Image;
		public btnHeat:Button;
		public btnChulu:Button;
		public btnChu_anse:Button;
		public starNode:Image;
		public btnChuLuFourStar:Button;
        public referenceClass:Array<any>=[Image, Button, View, Sprite, Label, 
				]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/lightAnimScene");
        }
    }
    REG("ui.test.lightAnimSceneUI",lightAnimSceneUI);
    export class MainSceneUI extends View {
        public referenceClass:Array<any>=[View, Image]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/MainScene");
        }
    }
    REG("ui.test.MainSceneUI",MainSceneUI);
    export class RankListUI extends View {
		public mlist:List;
		public testClip:Clip;
        public referenceClass:Array<any>=[List, Clip, View, Sprite, Image, 
				Box, Label]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/RankList");
        }
    }
    REG("ui.test.RankListUI",RankListUI);
    export class resuletUI extends View {
		public star1:Sprite;
		public star2:Sprite;
		public star3:Sprite;
		public score:Label;
		public btndoubleGet:Button;
		public getMoney:Label;
		public btnget:Button;
		public scoreType:Image;
        public referenceClass:Array<any>=[Sprite, Label, Button, Image, View, 
				Box]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/resulet");
        }
    }
    REG("ui.test.resuletUI",resuletUI);
    export class UIAuctionUI extends View {
		public saler1:Sprite;
		public saler2:Sprite;
		public saler3:Sprite;
		public money:Label;
		public maxMoney:Label;
		public btnsale:Button;
		public btnNext:Button;
		public btnmaxMoney:Button;
		public title:Image;
        public referenceClass:Array<any>=[Sprite, Label, Button, Image, View, 
				Box]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/UIAuction");
        }
    }
    REG("ui.test.UIAuctionUI",UIAuctionUI);
    export class UIExhibitionUI extends View {
		public btnsale:Button;
        public referenceClass:Array<any>=[Button, View, Image, Box]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/UIExhibition");
        }
    }
    REG("ui.test.UIExhibitionUI",UIExhibitionUI);
    export class UIGameStartUI extends View {
		public btnGamStart:Button;
		public btnAdvanced:Button;
        public referenceClass:Array<any>=[Button, View, Image]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/UIGameStart");
        }
    }
    REG("ui.test.UIGameStartUI",UIGameStartUI);
    export class UIOptSceneUI extends View {
		public nodeGameStart:Box;
		public progressBarParent:Image;
		public maskZise:Image;
		public maskFen:Image;
		public maskLvse:Image;
		public nodeStar:Image;
		public scaleStar:ui.scaleStarUI;
		public imgGood:Image;
		public imgPerfect:Image;
		public nodeAddTexuture:Box;
		public btnAuction:Button;
		public listAddTexture:List;
		public addTextureTip:Label;
		public addTextureArrow:Box;
		public addTextureArrowAnim:ui.animMoveUI;
		public nodeAddColor:Box;
		public listColors:List;
		public nodeColor:Box;
		public btnColor1:Button;
		public addColorTip:Label;
		public btnaddColorNext:Button;
		public nodeShap:Box;
		public shapcenterTip:Label;
		public btnCuihuo:Button;
		public scaleAnim:ui.scaleBtnUI;
		public tipCuihuo:Image;
		public nodearrow:Box;
		public arrowAnim:ui.animMoveUI;
		public nodePolish:Box;
		public btnPolishFinish:Image;
		public btnPolishAuction:Image;
		public btnPolishAddColor:Image;
		public polishFinishTip:Label;
		public btnPlishFinishAdvance:Image;
		public btnGoHome:Button;
		public lineParent:Box;
		public line:Image;
        public referenceClass:Array<any>=[Box, Image, Button, List, Label, 
				View, Sprite]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/UIOptScene");
        }
    }
    REG("ui.test.UIOptSceneUI",UIOptSceneUI);
}