/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import LinghtANimSceneUI from "./LinghtANimSceneUI"
import GameUI from "./script/GameUI"
import ListTest from "./ListTest"
import UIOptScene from "./script/UIOptScene"
import { EffectAnimation } from "laya/display/EffectAnimation"
import { ClassUtils } from "laya/utils/ClassUtils";
import { ui } from "./ui/layaMaxUI";
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="test/lightAnimScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = ClassUtils.regClass;
		reg("ui", ui);
        reg("LinghtANimSceneUI.ts",LinghtANimSceneUI);
        reg("script/GameUI.ts",GameUI);
        reg("ListTest.ts",ListTest);
        reg("script/UIOptScene.ts",UIOptScene);
        reg("laya.display.EffectAnimation",EffectAnimation);
    }
}
GameConfig.init();